name: ci
on: [push,pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: auth1
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: auth1_test
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
        id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Connect to PostgreSQL
      run: node client.js

    - name: Generate
      run: ./generate.sh
      
    - name: Generate again
      run: ./generate.sh
      
    - name: Source
      run: source dev_env
      
    - name: Test
      run: go test -v ./gql/...
