name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: auth1
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: auth1_test
          POSTGRES_HOST: localhost
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: mkdir 
      run: mkdir -p /home/runner/work/github.com/sunfmin
      
    - name: cp
      run: cp -r /home/runner/work/auth1/auth1 /home/runner/work/github.com/sunfmin
      
    - name: cd
      run: cd /home/runner/work/github.com/sunfmin/auth1
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: generate
      run: ./generate.sh
      
    - name: dev_env
      run: source dev_env
      
    - name: Test
      run: go test -v ./gql/...
